### ISSUE TITLE
MOODLE_400_STABLE branch calls datasource add_all_from_entities

### ISSUE THREAD

**Issue by nwp90** [danmarsden/moodle-mod_attendance#629] opened 2022-09-21 22:23 UTC
core_reportbuilder\datasource does not have add_all_from_entities in 4.0 so MOODLE_400_STABLE branch should not try to use it

**Comment by danmarsden** [comment] 2022-09-21 22:34
duplicate of #611 - are you using the latest version?

**Comment by nwp90** [comment] 2022-09-22 23:17
Thought we were; will check.

**Comment by nwp90** [comment] 2022-09-22 23:17
Oh hang on, no, that was pre the update we're currently doing.

**Comment by danmarsden** [comment] 2022-09-23 03:08
cool - flagging this as closed then :-)

**Closed as completed by danmarsden** 2022-09-23 03:08 UTC
