### ISSUE TITLE
Attendance Point and Percentage Calculation

### ISSUE THREAD

**Issue by chemsaravanan** [danmarsden/moodle-mod_attendance#217] opened 2016-08-30 06:00 UTC
I am novice to Moodle Attendance. In report generation, it does not take the number of sessions attended by the students. The screenshot is there. Pls Help.
![1](https://cloud.githubusercontent.com/assets/21329379/18077720/20b26e68-6ea5-11e6-8f26-03868392f8e3.png)

**Comment by danmarsden** [comment] 2016-08-30 06:09
yes - the reports have recently changed/improved but the screenshots in the plugins db haven't been updated yet. I'll try to do that soon - thanks.

**Comment by danmarsden** [comment] 2016-08-30 06:21
in fact - I think I misunderstood what you were saying there. What is your max grade and grade type set to within the attendance?

**Comment by danmarsden** [comment] 2016-08-30 06:47
also check the settings tab and make sure you have some values set for the point values used in your status set.

**Comment by chemsaravanan** [comment] 2016-08-30 11:38
![1](https://cloud.githubusercontent.com/assets/21329379/18087730/3e4c6616-6ed4-11e6-9180-4e56eb5af2f6.jpg)
The setting page is enclosed for your perusal.

**Comment by danmarsden** [comment] 2016-08-31 22:41
right - so the "Grade" is set to "none" - so it doesn't know how to calculate it. I guess we should probably hide those columns in the report when the grade is set to "none"

**Comment by danmarsden** [comment] 2016-09-20 06:05
I've pushed a commit that hides those columns when no grade is set.

**Comment by antonio-c-mariani** [comment] 2016-11-26 04:25
Hi, Dan

This was discussed in #163. The idea was to separate the concepts of points and grades. In this sense, no matter what is set up in the grade settings, the points should always be displayed. The reports were redesigned to work correctly even in this case of selection "none" to grade setting. I did several tests and this problem never happened before.

I could not reproduce the problem. We need more information to identify what might have caused this failure.  Maybe something about the status sets. I would like to see the statusset settings and the "all" report tab.

Would you like to review the issue #163? If not, I would appreciate if you could undo this commit.

**Comment by antonio-c-mariani** [comment] 2016-11-28 00:18
I have reviewed the code and I really don't know what could cause this failure. It have tried several different scenarios but none of them have shown the same failure.
Some questions:
* What's your Moodle version?
* What's your Attendance module version?
* What's your database (Mysql, Posgres, ..)?
* Could you activate the Moodle debugging mode to see possible warning messages?
* Could you attach a printscreen of "Settings" tab?

**Comment by danmarsden** [comment] 2016-11-29 04:40
I'm pretty sure I managed to reproduce this when I added that patch - I'm pretty busy at the moment but will try to find time to reproduce again - I wonder if it was for pre-existing attendances set to use no-grade before upgrading to the latest code?

**Comment by danmarsden** [comment] 2016-11-29 07:26
hmmm... I can't find a way to reproduce the state shown in the image now either - although I'm sure I did see this somehow. In any case I agree the patch was incorrect so I've reverted it for now.

Interesting to see the image only shows "present/absent" totals down the bottom so there's definitely a change to the information on the settings tab. I can't find a way to get " /1" showing in the points column either - only "0/1"

**Comment by antonio-c-mariani** [comment] 2016-11-30 01:21
All calculations are made by the "summary" class. There are no references to grade settings there so the failure seems to have nothing to do with this.
 
The user points are calculated by the SQL fragment below:

SELECT atl.studentid AS userid, COUNT(DISTINCT ats.id) AS numtakensessions,
                        SUM(stg.grade) AS points, SUM(stm.maxgrade) AS maxpoints
                   FROM {attendance_sessions} ats
                   JOIN {attendance_log} atl ON (atl.sessionid = ats.id)
                   JOIN {attendance_statuses} stg ON (stg.id = atl.statusid AND stg.deleted = 0 AND stg.visible = 1)
                   JOIN (SELECT setnumber, MAX(grade) AS maxgrade
                           FROM {attendance_statuses}
                          WHERE attendanceid = :attid2
                            AND deleted = 0
                            AND visible = 1
                         GROUP BY setnumber) stm
                     ON (stm.setnumber = ats.statusset)

From the image we can see that there is one taken session (column "Taken sessions") and the max points of which user is one (denominators of the column "Points") which means the sql variables "numtakensessions" and "maxpoints" are both equal to one. But the numerators of the "Points" column are all blanks which seems to indicate that the sql variable "points" is not a number (may be blank or null). These numerators are calculating by the sum of the "grade" column of the "attendance_statuses" table, which are definitely not all null as we can see in the session colunms details and the summary row. This leads us to a kind of contradiction because in tests I have done (Mysql and Postgres) the sum is not null if at least one of the values is a number.

I think it's necessary to inspecting the database records in order to know what might be happening.

**Comment by danmarsden** [comment] 2016-11-30 08:38
thanks Antonio - if we don't hear back from the original reporter we can just close this off.

**Comment by danmarsden** [comment] 2017-02-02 08:01
closing due to lack of response from reporter - we can reopen this again if we can confirm where the problem is. Thanks.

**Closed by danmarsden** 2017-02-02 08:01 UTC
Labels: bug
