### ISSUE TITLE
Not rescaling to the size of the screen you're using

### ISSUE THREAD

**Issue by maireanu** [danmarsden/moodle-mod_attendance#286] opened 2018-01-04 09:56 UTC
The plugin is not correctly displaying data if the resolution of the screen is big .
Tested on Safari, Chrome, Firefox with screen res of 2560 x 1600.

<blockquote class="imgur-embed-pub" lang="en" data-id="7ocu8OZ"><a href="//imgur.com/7ocu8OZ">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

On lower resolution the data is displayed correctly.

Moodle version : Moodle 3.4 (Build: 20171113)
Plugin version : Attendance  3.4.1
Theme used : Clean

**Comment by danmarsden** [comment] 2018-01-04 20:49
what Moodle version is this, what version of Attendance, and what theme is being used? - please ensure you always provide this sort of information whenever reporting a Moodle issue.

**Comment by maireanu** [comment] 2018-01-05 06:34
Sorry about that, I have edited the post with all the information, if you need more please let me know

**Comment by danmarsden** [comment] 2018-01-07 21:16
I can't reproduce this with the clean theme and the latest version of the attendance plugin in firefox or chrome. Please check to make sure you don't have any customcss added to your theme that might be causing this. Please also try with alternate browsers to see if you can reproduce the issue in multiple browsers. As I am unable to reproduce this you may need to resolve this yourself - please let us know if you find something within the attendance css that is causing it.

**Comment by danmarsden** [comment] 2018-01-21 21:59
closing as I cannot reproduce this and no feedback from reporter in 2 weeks. Happy to reopen again if someone else can confirm this is an issue though.

**Closed by danmarsden** 2018-01-21 21:59 UTC
