### ISSUE TITLE
Auto marking scheduled task failure

### ISSUE THREAD

**Issue by jmatikainen** [danmarsden/moodle-mod_attendance#617] opened 2022-09-07 12:22 UTC
We are getting a failed scheduled task using the latest 3.11.14 version of the Attendance plugin:

Scheduled task failed: Check for attendance sessions that require auto marking (mod_attendance\task\auto_mark),Call to undefined function profile_load_data()

This happens if any session has "Set unmarked at end of session" selected for automatic marking.

**Comment by haietza** [comment] 2022-09-07 18:13
We are seeing this on version 3.11.12 as well. I think simply adding 

`require_once($CFG->dirroot . '/user/profile/lib.php');`

at the top of mod/attendance/classes/structure.php resolves the error.

**Comment by danmarsden** [comment] 2022-09-07 23:49
thanks for the report - looks like a regression from #601 - I've just pushed a fix into the branches here in github but will look at republishing another version into the plugins db maybe tomorrow.

**Comment by wilenius** [comment] 2022-09-08 07:17
Unfortunately this fix is not working for us. With 3.11 and with 4.0.3, only the last student of the attendance list gets the automark (as per https://github.com/danmarsden/moodle-mod_attendance/issues/529), and with debugdisplay on, there is the following error message in the user interface:

`
Did you remember to make the first column something unique in your call to get_records? Duplicate value '31' found in column 'studentid'.
line 1039 of /lib/dml/pgsql_native_moodle_database.php: call to debugging()
line 1500 of /lib/dml/moodle_database.php: call to pgsql_native_moodle_database->get_records_sql()
line 1451 of /lib/dml/moodle_database.php: call to moodle_database->get_records_select()
line 1100 of /mod/attendance/classes/structure.php: call to moodle_database->get_records()
line 88 of /mod/attendance/classes/output/take_data.php: call to mod_attendance_structure->get_session_log()
line 98 of /mod/attendance/take.php: call to mod_attendance\output\take_data->__construct()`

**Comment by schach** [comment] 2022-09-08 12:55
The errors @wilenius mentioned are caused by duplicate entries in the attendance_log table.
We have noticed these have been created by the plugin's auto_mark task after we updated to Attendance version 3.11.11.
Only the last student of the attendance list gets the automark and the number of duplicates is the same as the number of users in the session.

The source of this problem lies in classes/task/auto_mark.php and is a regression caused by https://github.com/danmarsden/moodle-mod_attendance/commit/01540487bd120442913112c0477985ccb76930fb

The stdClass object $newlog is created only once. Instead there should be a new object created for every user.

There is this code block that creates the $newlog object and assigns some values to it before iterating over the users.
```
$newlog = new \stdClass();
$newlog->timetaken = $now;
$newlog->takenby = 0;
$newlog->sessionid = $session->id;
$newlog->remarks = get_string('autorecorded', 'attendance');
$newlog->statusset = implode(',', array_keys( (array)$att->get_statuses()));
```

This block should probably be moved inside the loop in the following two places:
https://github.com/danmarsden/moodle-mod_attendance/blob/MOODLE_401_STABLE/classes/task/auto_mark.php#L165
https://github.com/danmarsden/moodle-mod_attendance/blob/MOODLE_401_STABLE/classes/task/auto_mark.php#L233

**Comment by haietza** [comment] 2022-09-08 15:53
We are seeing the same issue with the duplicate DB record error and only the last student being auto marked.

**Comment by danmarsden** [comment] 2022-09-08 20:47
thanks for the report! - I wish I had time to write some good solid unit tests to help prevent these sorts of regressions...maybe one day.

I'd also assumed (badly) that people were not using the auto-marking as there were a few people reporting issues, obviously that wasn't the case either - great to hear it was being used succesfully previously.

Thanks for the analysis too, I should have some time today to test and push through a fix.

**Comment by danmarsden** [comment] 2022-09-08 21:09
hmm - looking at this a bit more, I can see how this might occur when automarking is set to point at an activity completion but not always in other cases - @haietza and @schach can you please confirm which automarking settings you are using?

**Closed as completed** 2022-09-08 21:23 UTC

**Comment by danmarsden** [comment] 2022-09-08 21:31
ah - never mind - I see where the issue was - @schach was going down the right track there - thanks, I've pushed a fix for this into the repo, will just see if I can knock together a clean up script to remove the incorrect duplicate records before I push the update to the plugins db.
