### ISSUE TITLE
Report 

### ISSUE THREAD

**Issue by BillyBobJoe19** [danmarsden/moodle-mod_attendance#653] opened 2023-01-25 00:47 UTC
When we go to report, they are able to access all students, even though I changed their access to access only their group.

**Comment by danmarsden** [comment] 2023-01-25 01:00
Hi there,
Please provide more information.

- What Moodle version are you using?
- What version of the Attendance plugin do you have installed?
- what is your course group mode set to?
- what is the attendance activity group mode set to?
- What specifically did you change when you say "I changed their access"

thanks!

**Comment by BillyBobJoe19** [comment] 2023-01-25 01:08
Hi Dan,

Thanks for the quick response! 

- Moodle version 4.0.6
- Attendance Version 4.0.10
- Course group set to Separate Groups, Force Yes, Default Grouping None
- Activity group set to separate groups
- Changed by disallowing the role from "View All Courses"

**Comment by danmarsden** [comment] 2023-01-25 01:17
That last point sounds wrong 'view all courses' - maybe ask for help in the forums?

**Comment by BillyBobJoe19** [comment] 2023-01-25 01:23
Sorry - meant [view all groups](https://docs.moodle.org/400/en/Capabilities/moodle/site:accessallgroups).

It works correctly in the normal attendance setting, but under report, it shows all students, not just those in the group

**Comment by danmarsden** [comment] 2023-01-25 02:30
Thanks - this sounds like it could be a duplicate of #637 which is fixed in the MOODLE_400_STABLE branch here in github but it doesn't look like I've pushed out a new release to the plugins db since that fix on the 4.0 branch - feel free to grab the latest version here in github for your Moodle release and see if it fixes it for you.

**Comment by BillyBobJoe19** [comment] 2023-01-26 01:40
@danmarsden - when I go to upload the ZIP, it has a validation error. Do you know of a work around? 

I am also currently on the 4.0.10, so I have been on the 4.0 - sorry for all the questions, just trying to learn!

**Comment by danmarsden** [comment] 2023-01-26 08:41
I've just published a new release to the plugins db - let me know if the published release fixes the issue you had - thanks.

**Comment by BillyBobJoe19** [comment] 2023-01-26 12:52
Hi Dan,
That worked! Thanks for the help. Have a great day!

**Comment by danmarsden** [comment] 2023-01-26 21:44
cool - thanks for confirming that.

**Closed as completed by danmarsden** 2023-01-26 21:44 UTC
