### ISSUE TITLE
Allow timezone of a session to be specified.

### ISSUE THREAD

**Issue by cwarwicker** [danmarsden/moodle-mod_attendance#305] opened 2018-05-29 11:43 UTC
Hi,

If I were to add in the following features to a pull req:

- Setting to set different timezone of a session
- Setting to have attendance marked automatically when accessing the course during the session times

(And assuming they work of course!) Would they be accepted into the plugin?

Conn

**Comment by danmarsden** [comment] 2018-05-29 21:29
Hi @cwarwicker, pull requests are always welcome, but obviously will go through an initial review first. Ideally new features should have corresponding behat tests too.

It does sound like you haven't looked at the existing code-base though? - the option to automatically mark when accessing the course during session times is already supported. You can even create an attendance session for the past and have it process the logs from that day to generate the attendance. The automatic marking process could potentially do with further improvements though.

thanks!

**Comment by cwarwicker** [comment] 2018-05-30 20:58
Ok, I couldn't see that feature when I looked before.

**Comment by danmarsden** [comment] 2018-05-30 22:14
understandable - the documentation on attendance is rubbish. Hopefully we'll improve it eventually!

The automatic marking requires student marking to be enabled at the site level - admin > activities > attendance > "studentscanmark"

then when creating a session and enabling student marking you should see a couple of automatic marking options - click on the help text to understand how they work.

both require cron to be running.

**Comment by danmarsden** [comment] 2018-07-27 01:39
closing this as a duplicate of #202

**Closed by danmarsden** 2018-07-27 01:39 UTC
Labels: enhancement
