### ISSUE TITLE
Disable minutes field unless Specified time in minutes is selected

### ISSUE THREAD

**Issue by kwaffles77** [danmarsden/moodle-mod_attendance#454] opened 2020-02-04 17:10 UTC
Under Student recording>Show more, there is a 
setting labeled "Prevent students sharing IP address" along with the options, "Yes", "No", and "Specified time in minutes to release IP".  To the right of this is a text box to enter the number of minutes if the "Specified time in minutes to release IP" option is selected.  If "Yes" or "No" is selected, it is still possible to enter something in this field and if something is entered mistakenly, it results in an error when students try to record their attendance. The field should be disabled or disregarded unless the appropriate option is selected. 

![image](https://user-images.githubusercontent.com/60664724/73768557-38d5b080-4747-11ea-957f-8eb02f8265a8.png)

![image](https://user-images.githubusercontent.com/60664724/73768414-edbb9d80-4746-11ea-8cfc-fff21dd83c2a.png)
![image](https://user-images.githubusercontent.com/60664724/73768606-4e4ada80-4747-11ea-904e-8e3811cd41da.png)

**Comment by danmarsden** [comment] 2020-02-04 21:22
this is a duplicate of #427 - there's a bug in the sql query. It's fixed in the latest versions of the plugin.

**Closed by danmarsden** 2020-02-04 21:22 UTC
