### ISSUE TITLE
Self-Marking Issue

### ISSUE THREAD

**Issue by Tigger996** [danmarsden/moodle-mod_attendance#423] opened 2019-09-04 16:26 UTC
Using Moodle 3.7.1

I have set up a session that has Allow students to record own attendance.
Disabled automatic marking
Set a password and included a QR Code.

When I try to use it, I get "This session is not currently available for self-marking."

Am I missing something or is this a bug?
Thanks

**Comment by kaitkrull** [comment] 2019-09-06 06:16
I can confirm that this is happening. In order for this to work we had to ask our students to log into Moodle first and after that scan the QR code. Then they were redirected to the right page and were able to mark their attendance. 

Could there be a fix done which would redirect the user to log in page first and after logging in they are redirected back to the Attendance marking?

**Comment by danmarsden** [comment] 2019-09-08 23:11
I need a bit more info here...
what version of the attendance code, what settings are in use, is the session "open" - usually students can only self-mark during an open session eg if the session is 9am - 10am - the will not be able to self-mark at 8:58am (Issue #297 covers suggested improvements to this.)

**Comment by kaitkrull** [comment] 2019-09-09 13:46
We are using Moodle 3.7.1 and Attendance 3.6.7 (2019062200). We have the same settings set as Tigger996 described for our attendances and the students use the QR codes in order to register. After some more testing I think I now understand on what circumstances the user would get this kind of notice ("This session is not currently available for self-marking."). 

It turns out that this happens when you have allowed **guest access** to the course which result user being redirected to the course front page and displayed the warning. After that the user either has to log in and find the right activity or use the method described earlier by me.

So, my apologies for mixing things up but could there be more descriptive warning text (like telling the user that you have to be logged in for accessing this activity) or some other kind of implementation for forcing the user to log in?

**Comment by Tigger996** [comment] 2019-09-09 14:52
In my case, I figured out what the issue is.  In my test I did not set a time.  OOPS!

**Comment by danmarsden** [comment] 2019-09-10 00:58
cool - I'm closing this as the original reported issue is really user-error. @kaitkrull your issue sounds like correct behaviour too, but feel free to create a new issue to cover improving the warnings when the user is logged in as the guest user.

**Closed by danmarsden** 2019-09-10 00:58 UTC
