### ISSUE TITLE
Relationship to Custom Reports

### ISSUE THREAD

**Issue by chihiro-sugita** [danmarsden/moodle-mod_attendance#709] opened 2023-10-24 08:50 UTC
Installing the latest plugin(2023020107) causes errors in custom reports.
My Moodle : Moodle 4.1.5+ (Build: 20230822)
Several people in my organization have experienced the same phenomenon.

”Coding error detected, it must be fixed by a programmer: Complex columns must have an alias"

**Comment by danmarsden** [comment] 2023-10-24 09:18
This is a duplicate of #694

**Closed as completed by danmarsden** 2023-10-24 09:18 UTC
