### ISSUE TITLE
Add API method to retreive session id's by AttendanceInstanceId

### ISSUE THREAD

**Issue by pete1854** [danmarsden/moodle-mod_attendance#554] opened 2021-09-02 09:23 UTC
Hi,
Several API methods currently depend on the session id be provided. However, there seems to be no current API function to get all session id's for an attendance instance in a course.

Kind regards,
Peter

**Comment by danmarsden** [comment] 2021-09-02 09:55
Uh.. isn't this a duplicate of https://github.com/danmarsden/moodle-mod_attendance/issues/549#issuecomment-903331709

**Comment by danmarsden** [comment] 2021-09-02 09:59
Oh I see - you want a get _sessions function rather than a get_course_module. Cool. Pull requests are welcome!

**Closed as completed** 2021-09-13 23:06 UTC
Labels: enhancement
