### ISSUE TITLE
Grade for taken attendance

### ISSUE THREAD

**Issue by cangeli-emnt** [danmarsden/moodle-mod_attendance#447] opened 2019-12-10 10:08 UTC
I have this situation: 

- Attendance with 4 lessons and maximum grade 12
- User 1 with 4 lessons taken with "presence", so grade is 12
- User 2 with only one lesson taken with "presence" (the other ones are unset) and grade is 12.

User 2 should have just 3 as grade. Why User 1 and 2 have the same grade? 

This is a big problem because I cannot use the attendance grade for complete course condition.

**Comment by danmarsden** [comment] 2019-12-10 21:13
Hi There, you haven't provided enough information here that points to this being a bug rather than the configuration you have used within your attendance activity. The best place for these sorts of "questions" rather than specific bug reports is the support forum on moodle.org here:
https://moodle.org/mod/forum/view.php?id=741

I'm closing this here as "not a bug" but please create a new post in the forum linked above and someone might be able to help further.

Please note - the forums are supported by volunteers - if it takes too long for you to get a response you could ask your local Moodle Partner to provide commercial level support and help further.

thanks!

**Closed by danmarsden** 2019-12-10 21:13 UTC

**Comment by caemnt** [comment] 2019-12-13 11:06
Please, see this discussion https://moodle.org/mod/forum/discuss.php?d=394592
There are more details.

Thank you!
