### ISSUE TITLE
Sessions set to "automatic marking: set unmarked at end of session" cannot be edited

### ISSUE THREAD

**Issue by webers-technikum-wien** [danmarsden/moodle-mod_attendance#328] opened 2018-09-10 10:28 UTC
Moodle version: 3.5.2
Plugin version: 2018051401

**Bug description:** When a session is set to "automatic marking: set unmarked at end of session", it cannot be edited any more, since when trying to save the session it will always claim "The status set in use does not have a status to use when not marked."

**How to reproduce:**

1. Create a new status set including one item where "automatically set when not marked" is checked.
2. Create a new session using that status set and enable "automatic marking: set unmarked at end of session"
3. Save the session
4. Edit this session again and try to save it again - it will not be possible, error: "The status set in use does not have a status to use when not marked."

-------------------

Also, another smaller bug when creating status sets: when you try to click "add" and only entered "acronym" and "description" for the current item, you will get "error writing database"

**Comment by danmarsden** [comment] 2018-09-10 22:45
Thanks - this has already been fixed in the latest code available in github - although I have created issue #329 in relation to the status set editing form - I really don't like that form and it could do with some UX improvements!

You can get the latest version of the code from github here, I am also working on adding Mobile app support to the plugin and when that is done (hopefully withing the next 3 weeks) I will be releasing the updated code into the moodle.org plugins database.

**Closed by danmarsden** 2018-09-10 22:45 UTC

**Comment by webers-technikum-wien** [comment] 2018-09-11 11:05
I just installed version 2018072701, but it seems to have the same problem...

**Comment by danmarsden** [comment] 2018-09-11 21:32
I can't reproduce this with the code in the master branch here in github.

Please check to make sure the status set in use in your session has a status that is set correctly.

If you are still having issues, please provide a bit more info/screenshots of settings pages/ exact Moodle version, database type in use, make sure debugging on your site is turned on with developer level set and let me know if any other information is reported.

Please note - the item you mention with the title "Also, another smaller bug" is still an issue and I have created Issue #329 to deal with this.

**Comment by webers-technikum-wien** [comment] 2018-09-12 09:58
exact moodle version: Moodle 3.5.1+ (Build: 20180831)
database type: pgsql

version of the plugin:
![image](https://user-images.githubusercontent.com/13886080/45417708-168b5080-b683-11e8-9a7c-58a024be5663.png)

status set:
![image](https://user-images.githubusercontent.com/13886080/45417715-1e4af500-b683-11e8-8361-01fde0711c72.png)

session creation: be aware that the **creation of the session is not a problem, but when you then try to edit the session after creating it**, the error happens:

![image](https://user-images.githubusercontent.com/13886080/45417594-d75cff80-b682-11e8-8c96-61a025b203df.png)


it should not make any difference if i uninstall and reinstall the mod instead of just upgrading to the latest master branch version, right?

**Comment by danmarsden** [comment] 2018-09-12 10:35
thanks - the screenshots helped, I couldn't reproduce it locally but I did find something that looks like it might have been the cause. I've just pushed a fix into the github branch here - let me know if you get a chance to update again and test to see if it is now fixed for you.

thanks for your help!

**Comment by webers-technikum-wien** [comment] 2018-09-12 10:47
yes, this fixed it, thanks :)

**Comment by danmarsden** [comment] 2018-09-12 21:59
great thanks for the confirmation and help!
