### ISSUE TITLE
Moodle 31 - upgrade - Cannot redeclare create_calendar_events()

### ISSUE THREAD

**Issue by roperto** [danmarsden/moodle-mod_attendance#245] opened 2017-03-07 06:06 UTC
It happens after the `++ Success ++` and the plugin is installed successfully.

```
$ php /var/www/moodle/html/admin/cli/upgrade.php --non-interactive
-->mod_attendance
++ Success ++
PHP Fatal error:  Cannot redeclare create_calendar_events() (previously declared in /var/www/moodle/html/mod/attendance/db/upgradelib.php:25) in /var/www/moodle/html/mod/attendance/classes/calendar_helpers.php on line 77
PHP Stack trace:
PHP   1. {main}() /var/www/moodle/html/admin/cli/upgrade.php:0
PHP   2. admin_apply_default_settings() /var/www/moodle/html/admin/cli/upgrade.php:187
PHP   3. admin_get_root() /var/www/moodle/html/lib/adminlib.php:7300
PHP   4. require() /var/www/moodle/html/lib/adminlib.php:7279
PHP   5. core\plugininfo\mod->load_settings() /var/www/moodle/html/admin/settings/plugins.php:45
PHP   6. include() /var/www/moodle/html/lib/classes/plugininfo/mod.php:89
PHP   7. require_once() /var/www/moodle/html/mod/attendance/settings.php:28

Fatal error: Cannot redeclare create_calendar_events() (previously declared in /var/www/moodle/html/mod/attendance/db/upgradelib.php:25) in /var/www/moodle/html/mod/attendance/classes/calendar_helpers.php on line 77

Call Stack:
    0.0008     390344   1. {main}() /var/www/moodle/html/admin/cli/upgrade.php:0
    1.2186   31082504   2. admin_apply_default_settings() /var/www/moodle/html/admin/cli/upgrade.php:187
    1.2186   31082504   3. admin_get_root() /var/www/moodle/html/lib/adminlib.php:7300
    2.8296   32715320   4. require('/var/www/moodle/html/admin/settings/plugins.php') /var/www/moodle/html/lib/adminlib.php:7279
    3.0749   33163568   5. core\plugininfo\mod->load_settings() /var/www/moodle/html/admin/settings/plugins.php:45
    3.0750   33168768   6. include('/var/www/moodle/html/mod/attendance/settings.php') /var/www/moodle/html/lib/classes/plugininfo/mod.php:89
    3.0754   33232824   7. require_once('/var/www/moodle/html/mod/attendance/lib.php') /var/www/moodle/html/mod/attendance/settings.php:28
```

**Comment by danmarsden** [comment] 2017-03-08 06:08
thanks - this is a duplicate of #214 but it looks like it didn't get backported to the 3.1 branch which I've just done now.

**Closed by danmarsden** 2017-03-08 06:08 UTC
