### ISSUE TITLE
Error in installation process with Persian lang

### ISSUE THREAD

**Issue by parsa25eng** [danmarsden/moodle-mod_attendance#508] opened 2020-12-06 18:27 UTC
Hi,
I have installed moodle on ubuntu 18.04 and php7.2
when I try to install Attendance module this error occurs.
`
INSERT INTO mdl_attendance_statuses (attendanceid,acronym,description,grade,visible,deleted) VALUES(?,?,?,?,?,?)
[array (
0 => 0,
1 => 'غ.م',
2 => 'غیبت موجه',
3 => 1,
4 => 1,
5 => 0,
)]
Error code: dmlwriteexception
`
I will so thankful if guide me to the solution.

**Comment by danmarsden** [comment] 2020-12-06 21:07
What version of Moodle and what version of the attendance plugin are you using? - please make sure you're using the latest version of the Attendance plugin available here in github which should prevent the fatal error.

Please also review the comments on issue #394 for the cause of this and how you can fix the underlying issue in hte Perisan Lang pack.

**Comment by danmarsden** [comment] 2022-08-29 01:40
closing as this should not be an issue with the attendance code anymore - I'm still open to increasing the acronym field length but no one has actually asked for that yet...

**Closed by danmarsden** 2022-08-29 01:40 UTC
