### ISSUE TITLE
Sessions not appearing in calendar when group mode forced

### ISSUE THREAD

**Issue by jeffreychen24** [danmarsden/moodle-mod_attendance#306] opened 2018-06-07 19:12 UTC
I believe I found a bug in the code regarding automatically adding sessions into the calendar. Everything works fine using the default settings for courses, but when I create a course and change the settings to **separate groups** and **force group mode** it doesn't work. The sessions I create that are part of a group don't appear in the calendar even when I am enrolled in the group.

Additional info: If I create a course with default settings and add a session, it appears in the calendar. If I then change the settings for that course to separate groups and force group mode and add another session, both sessions appear in the calendar. If I go and delete the first session, both calendar events disappear.

**Comment by danmarsden** [comment] 2018-06-07 20:47
Thanks for the report, feel free to help us work on a fix for this.

**Comment by nwp90** [comment] 2018-06-24 21:16
Sounds to me more likely to be a bug in the core calendar display code than a problem with this plugin...

**Comment by danmarsden** [comment] 2019-01-29 02:50
can't reproduce this - presume it was an issue with the core version of Moodle you were using - let me know if you have any more info and we can look at reopening. Thanks.

**Closed by danmarsden** 2019-01-29 02:50 UTC
Labels: bug

**Comment by Christian-Morales-Zenteno** [comment] 2023-10-17 21:26
Hi @danmarsden,
I came across this issue in MoodleCloud versions 4.2.1 and 4.2.2 and can reliably reproduce it. Roles admin / teacher / course creator will not see attendance events in the calendar within a course under certain circumstances:
1. Course group mode is **Separate Groups**;
2. There are no Attendance activities **Type: All students**;

Any sessions **Type:  Group of students** will not be visible for the roles above in the calendar, only for students, regardless of whether there are other events in the calendar or not. However, if within the same course another attendance session exists with **Type: All students**, all other sessions will be visible. So, if you temporarily change the group mode to **Visible groups** and create a session **Type: All students**, and then revert the change to the group mode without deleting the session, all sessions will be visible in the calendar.

Does it sound like an attendance issue or Calendar issue?

**Comment by danmarsden** [comment] 2023-10-17 23:45
thanks for the added info - it probably needs a developer to investigate further to work out where that issue sits. It's not something I have time to look into right now but feel free to reach out privately if you would like to fund the time for a developer to look into it!

thanks!
