### ISSUE TITLE
Layout issue when updating attendance.

### ISSUE THREAD

**Issue by jgg9026** [danmarsden/moodle-mod_attendance#219] opened 2016-08-30 20:50 UTC
Precondition:
Course is using attendance resource.
Site is using clean 
Steps:
Go to the attendance resource.
Go to attendance settings by clicking in "Update this Attendance"
Change the language to French.
In the Restreindre la disponibilité section.
Click in the "Ajouter une restriction..." Button.
Check that the dialogue box, has a layout problem.
![screen shot 2016-08-30 at 3 43 28 pm](https://cloud.githubusercontent.com/assets/11038577/18106451/675afb72-6ec9-11e6-9e05-d76a517e1850.png)

**Comment by danmarsden** [comment] 2016-09-20 06:08
I'm relatively confident that you will probably see this behaviour on all activities - not just the attendance code. In any case the Attendance code is not responsible for the display of that particular pop-up or the language strings that are shown in the dialogue - closing this as "not a bug" with the attendance code. If this is still an issue you may want to check a standard plugin like "assignment" take a screenshot of that and report it to the moodle.org tracker (don't report it there using an attendance screenshot as that will confuse things.)

**Closed by danmarsden** 2016-09-20 06:08 UTC
