### ISSUE TITLE
Export as Excel leads to an error with empty sessions

### ISSUE THREAD

**Issue by adpe** [danmarsden/moodle-mod_attendance#321] opened 2018-08-07 06:08 UTC
Hello @danmarsden 

We've found while our testing, that there seems to be an error. The error turns up if you have per example three sessions and only two were filled out. After when you want to export the data and you selected "Select all sessions" it turns up following message:
![image](https://user-images.githubusercontent.com/9467708/43757293-ac7515fe-9a18-11e8-8cd7-1dd600995dc8.png)

The trick is to select additionally the "Include not taken sessions". But this doesn't make sense to me. If I want only the two attended sessions it's not possible to export only them.

Greets
Adrian

**Comment by danmarsden** [comment] 2018-08-08 01:04
Thanks for the report! - feel free to help us work on this.

**Comment by danmarsden** [comment] 2019-01-29 02:54
I couldn't reproduce what you were seeing here. If this is still an issue with the latest version please provide more details. eg - a list of the sessions and times set-up in the period, and then the period selected on the export form. (screenshots would help.) for now I'm closing this because I cannot reproduce it - thanks!

**Closed by danmarsden** 2019-01-29 02:54 UTC
Labels: bug
