### ISSUE TITLE
"invalidrecord" When updating settings of attendance session

### ISSUE THREAD

**Issue by Gigex** [danmarsden/moodle-mod_attendance#268] opened 2017-07-13 08:20 UTC
Any update to attendance session setting leads to an "invalidrecord" error.
The change to the session settings does happen, regardless of the error showing every time

> Debug info: SELECT * FROM {event} WHERE id = ?
> [array (
> 0 => 0,
> )]
> Error code: invalidrecord 

> Stack trace:
>     line 1526 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
>     line 1502 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
>     line 2662 of /calendar/lib.php: call to moodle_database->get_record()
>     line 95 of /mod/attendance/classes/calendar_helpers.php: call to calendar_event::load()
>     line 419 of /mod/attendance/classes/structure.php: call to attendance_update_calendar_event()
>     line 102 of /mod/attendance/sessions.php: call to mod_attendance_structure->update_session_from_form_data()

Moodle ver: 3.2
Attendance ver: 3.2.4

**Comment by danmarsden** [comment] 2017-07-13 08:37
Please try updating to the latest 3.2 stable branch here in github.

**Comment by danmarsden** [comment] 2017-07-13 21:46
this is a duplicate of #265 which has already been fixed here in the code in github.

**Closed by danmarsden** 2017-07-13 21:46 UTC
