### ISSUE TITLE
Error sql when use ipaddress filter

### ISSUE THREAD

**Issue by darioroig** [danmarsden/moodle-mod_attendance#428] opened 2019-09-18 07:26 UTC
In file www/mod/attendance/locallib.php go to row 462 and add clause 'AND' to sql
// Assume ATTENDANCE_SHAREDIP_FORCED.
            //DRG add AND to sql
            $sql = 'sessionid = ? AND studentid <> ? AND ipaddress = ?';

**Comment by danmarsden** [comment] 2019-09-18 08:10
this is a duplicate of #427 which has already been fixed in the git repository. thanks.

**Closed by danmarsden** 2019-09-18 08:10 UTC

**Comment by syusanjun** [comment] 2019-12-16 09:27
I am using Moodle 3.7.3.
Activities: Attendance is 3.7.1 (2019072402).
I can't save if I select yes or no in the Prevent students sharing IP address setting.
Is it necessary to enter the number of the ip address when selecting Yes or No?
