### ISSUE TITLE
Error ORA-00933

### ISSUE THREAD

**Issue by jaume77** [danmarsden/moodle-mod_attendance#503] opened 2020-11-16 15:11 UTC
Greetings from the Autonomous University of Barcelona (UAB)

First of all, thank you for developing the module, as it provides a highly demanded functionality among the teachers of our university.

In environments like ours, when Moodle is installed on an Oracle DB, an error occurs when a student enters a password.

![imagen](https://user-images.githubusercontent.com/2485232/99268262-36030280-2825-11eb-8540-e4cde53b152d.png)

![imagen](https://user-images.githubusercontent.com/2485232/99268309-487d3c00-2825-11eb-968b-b013400b2950.png)

The problem is in the **attendance.php** file:

`$sql = 'SELECT * FROM {attendance_rotate_passwords}'.
                 'WHERE attendanceid =? AND expirytime>? ORDER BY expirytime ASC LIMIT 2 ';`

In Mysql it works correctly, but in Oracle, the syntax "LIMIT 2" is not accepted

![imagen](https://user-images.githubusercontent.com/2485232/99268563-9b56f380-2825-11eb-944b-3d938753e3b6.png)

Thank you!

**Comment by danmarsden** [comment] 2020-11-16 21:00
this looks to be a duplicate of #459 which has already been fixed in the version here in github. Can you please update your code with the latest version available from github and confirm if it resolves your issue?

**Comment by jaume77** [comment] 2020-11-17 07:56
I updated the code to : 

`$sql = 'SELECT * FROM {attendance_rotate_passwords}'.
             ' WHERE attendanceid = ? AND expirytime > ? ORDER BY expirytime ASC';`
`$qrpassdatabase = $DB->get_records_sql($sql, ['attendanceid' => $id, time() - $attconfig->rotateqrcodeexpirymargin], 0, 2);`

as is in the latest version of github and it works correctly!

Thanks!

**Comment by danmarsden** [comment] 2020-11-17 09:13
Thanks

**Closed by danmarsden** 2020-11-17 09:13 UTC
