### ISSUE TITLE
Attendance in Moodle App - Sessions are displayed with an extra &nbsp after the date

### ISSUE THREAD

**Issue by ColinBruneau** [danmarsden/moodle-mod_attendance#426] opened 2019-09-06 08:15 UTC
When displaying sessions, all the sessions are like this:
30.09.19&nbsp;(lun) 08:30 - 18:00 Cine3

On Moodle App 3.7.0, french, plugin attendance 3.6.7

**Comment by danmarsden** [comment] 2019-09-08 23:06
can you please add a screenshot of the issue? - I'm not quite sure what the problem is here.

**Comment by ColinBruneau** [comment] 2019-09-09 07:34
I just realized that the &nbsp does not appear on my previous message...

![Screenshot_20190909_093048_com moodle moodlemobile](https://user-images.githubusercontent.com/22931956/64511522-cc17d080-d2e4-11e9-9e90-fc4b7991c900.jpg)

**Comment by danmarsden** [comment] 2019-09-10 01:00
thanks for the screenshot - I do remember seeing some issues related to this when working on adding mobile support - I vaguely recall there being a core mobile bug associated with this too.

Feel free to help us to work on this - pull requests or funding are always welcome. :-)

**Comment by ColinBruneau** [comment] 2019-10-11 14:48
Hey Dan,
For this bug I invetigated and found that the string 'strftimedmyw' used was set to '<nobr>%a %d %b %Y</nobr>'. So I used the string 'strftimedmy' instead and it fixed this bug (but removed the day display).

/var/www/html/moodle2019/mod/attendance/locallib.php
line1039
function construct_session_full_date_time($datetime, $duration) {
// Colin Bruneau: fix the weird &nbsp display
    //$sessinfo = userdate($datetime, get_string('strftimedmyw', 'attendance'));
    $sessinfo = userdate($datetime, get_string('strftimedmy', 'attendance'));
    $sessinfo .= ' '.attendance_construct_session_time($datetime, $duration);

    return $sessinfo;
}

**Comment by danmarsden** [comment] 2019-10-15 01:52
nice work tracking that down - the config for that comes from the lang pack - in en that is currently set to:
$string['strftimedmyw'] = '<nobr>%a %d %b %Y</nobr>';

Can you please check to see what your lang pack sets that value to? - does it have nbsp; directly in the string? - in which case we can report that as a bug in the lang string to amos?

**Comment by danmarsden** [comment] 2019-10-15 02:00
yeah - I've just had a look at the lang strings and it looks like that &nbsp is coming from the lang pack - I've just submitted a fix via amos.

**Comment by danmarsden** [comment] 2019-10-15 02:06
I'm closing this one as I've submitted a fix to amos for this.

**Closed by danmarsden** 2019-10-15 02:06 UTC
Labels: bug, mobilesupport

**Comment by martignoni** [comment] 2019-10-15 11:12
I've amended your AMOS submission to add the correct non-breaking space (UTF8 encoded).
