### ISSUE TITLE
Wrong yours set when DST

### ISSUE THREAD

**Issue by adamtppaw** [danmarsden/moodle-mod_attendance#462] opened 2020-03-29 20:53 UTC
Since we have started DST today, session start hours is set 1 hour too late.
To reproduce:
1. On the server set a timezone to some DST zone  (i.e. CEST) 
2. Set in set timezone in profile to "Warsaw"
3. Set session starting at 9.00
after that you will see that it has been set at 10:00.

**Comment by danmarsden** [comment] 2020-03-30 07:55
this sounds like it relates to the enhancement request in issue #202 - the timezone is pulled from the teacher that is logged in and setting the time/date in the original session. If a user changes their timezone, Moodle will automatically adjust the date as per the new users timezone (using Moodle's normal date/time handling processes.)

I suspect I'll close this as a duplicate, but if my assumption is incorrect feel free to clarify this further.

thanks,

**Comment by adamtppaw** [comment] 2020-03-30 11:22
I think the problem is slight different. It seems, like at the entry date and time was treated as CET, but later as CEST. Is the function usergetdate aware of DST? E.i. Usertime isn't. I'm guessing. No sure, if there is a source of problem.

**Comment by danmarsden** [comment] 2020-03-30 19:01
If you use a timezone with known DST and the user doesn't change their timezone manually then it should work correctly.
Please make sure your moodle site has an updated list of timezones as per:
https://docs.moodle.org/en/Location#Update_timezones

Maybe your Moodle site has old timezone data and the details around DST in your timezone are different from what Moodle is using?

**Comment by adamtppaw** [comment] 2020-03-30 21:40
We have proper timezone on server. I haven’t changed the timezone in my profile. Both are the same. On Saturday everything worked properly. We have problem starting from Saturday, when DST started.

**Comment by danmarsden** [comment] 2020-03-30 22:45
and... did you follow the moodledocs link I posted to make sure you have the correct timezone data stored in Moodle?

Unless you are able to provide more information or track this down further I'll probably need to close this as either "cannot reproduce" or a duplicate of #202 sorry!

**Comment by adamtppaw** [comment] 2020-03-31 08:59
Obviously, I have followed the instruction. We use Moodle for 17 years. Present instance of moodle is used since 2012 with 200 000 users in 5 universities. The only plugin where this 
problem occurred is attendance. So, I don't think the source of problem exists outside of the plugin. For now, i've problem with debugging over a vpn to my university . As soon as I resolve it, I will try to analyse the problem.

**Comment by adamtppaw** [comment] 2020-03-31 09:50
Some new info. It turns out, that problem occurs only if session date is Sun, 29th March 2020 -a first day of DST.
Session planned for next days works properly.

**Comment by danmarsden** [comment] 2020-03-31 19:18
nice work - that does seem to point to Moodle's handling being correct, but the timezone definition being incorrect.

reading that moodledocs link above I see that PHP is now responsible for pulling in the correct timezones. I see you mention that you read the link, but sorry to ask again... what version of PHP are you using - and have you updated the timezones in PHP using the Pecl packages linked?

**Comment by adamtppaw** [comment] 2020-03-31 21:35
We are using PHP Version 7.2.29-1+0~20200320.39+debian9~1.gbp513c2e.  Since it is not older the 6 months, I don't update timezones on production server. I've done in on staging (version 2019.3) but problem still exists.

**Comment by danmarsden** [comment] 2020-03-31 22:16
cool - I'm out of ideas then sorry - let me know if you work it out! :-)

**Comment by danmarsden** [comment] 2020-06-17 02:55
I'm closing this as cannot reproduce but as we rely on core Moodle code to handle dates I'd expect if there's an issue it will be in moodle core or php's date handling rather than the attendance activity - if you track this down further feel free to open a new issue with more information - thanks!

**Closed by danmarsden** 2020-06-17 02:55 UTC
