### ISSUE TITLE
Activity completion: When got the grade to pass & when teacher marks it as completed 

### ISSUE THREAD

**Issue by gonzalorti** [danmarsden/moodle-mod_attendance#330] opened 2018-09-11 00:37 UTC
Hello,

Very good plugin, congratulations.

I would like the attendance being necessary to get the certificate of the course (a minimun percentage like 80%). So I put into the attendance item a minimum grade to pass. It would be desirable in activity completion with conditions to be able to choose the option of the attendance passed.

Just now, the only option I find is when the student recieve in this item any calification. As it happens as soon as any activity is completed, this option is not very helpful (because the other activities are not completed yet).

Another helpful option should be that the teacher can mark the item as completed.

Thanks.

**Comment by danmarsden** [comment] 2018-09-11 01:08
I'm closing this as a duplicate of #251 which talks about something similar - allowing the activity completion to be based on sum of points to date rather than the way grading currently works.

I can't see this being something that I would spend volunteer time on - as mentioned on #251, changes to the grading processes need to be carefully considered and should ideally also include behat tests. Feel free to get in touch privately if you are willing to fund the time to work on this.

**Closed by danmarsden** 2018-09-11 01:08 UTC

**Comment by gonzalorti** [comment] 2018-09-12 22:11
I thought it would help to make it more useful. Thanks, anyway.

**Comment by danmarsden** [comment] 2018-09-12 22:55
sure - anything is possible and pull requests and or funding are always welcome - thanks!
