### ISSUE TITLE
User appears under all groups although belonging to only one group

### ISSUE THREAD

**Issue by spinozarabel** [danmarsden/moodle-mod_attendance#291] opened 2018-01-30 09:14 UTC
A user who belongs to only group appears when any group is selected, not just the group he belongs to. I have several groups mapped according to cohorts using the cohort sync method of enrolment and creating these groups. Further, as can be seen from the screen shot (attached) it appears in red and no records of this user exist for attendance. Strange. Any pointers to how I can debug this issue will be much appreciated.
(I do have a few other users also appear in red but show up only in their groups in attendance.

I have double checked the enrolment and the group memberships and all is as intended and unique.

<img width="616" alt="sketch" src="https://user-images.githubusercontent.com/16438408/35557545-6b807b9c-05cb-11e8-9e68-cc7a465deab9.png">

**Comment by danmarsden** [comment] 2018-01-30 21:36
That looks like a "temporary user" that you have created within the attendance activity. Temporary users are used to track attendance of users that do not have accounts in your Moodle site and are not "real users" and cannot be added as members of any group.

Have a look at the "temporary users" tab inside your attendance and you should see the user there.

closing this because it is expected behaviour.

**Closed by danmarsden** 2018-01-30 21:36 UTC

**Comment by spinozarabel** [comment] 2018-01-31 00:45
Dear Mr. Marsden,
First of all, thank you for your wonderful plugin and such prompt response. Also, allow me to apologize for wasting your time, as a seasoned computer user I should have checked that tab also. Finally, may I request you to include this in documentation, if not already there, since I did look for it in the documentation but failed to find any.
Kind regards,

**Comment by danmarsden** [comment] 2018-01-31 01:23
The documentation site is a public access wiki and anyone can update it:
https://docs.moodle.org/en/Attendance_activity

Feel free to improve the docs yourself - I don't typically have time to update it myself and tend to spend volunteer time on other tasks.
