### ISSUE TITLE
MOODLE_311_STABLE branch fails to installl in a moodle just upgraded to 3.11 in the same branch

### ISSUE THREAD

**Issue by IJOL** [danmarsden/moodle-mod_attendance#695] opened 2023-08-03 06:36 UTC
Salida de depuración habilitada
Descargando mod_attendance ...
<- https://moodle.org/plugins/download.php/28433/mod_attendance_moodle311_2021082610.zip
-> /var/www/moodledata/temp/core_plugin/code_manager/distfiles/5c554750d2795101a62ef0832de7e6ff.zip ... OK
Validando mod_attendance ... Error
[OK] Nombre del módulo externo que se debe instalar [attendance]
[OK] Versión del módulo externo [2021082610]
[Error] Versión de Moodle requerida [2021051700]
Instalación abortada debido a error de validación

contents of the version.php of the moodle in branch MOODLE_311_STABLE are as follows:

$version = 2021051715.06; // 20210517 = branching date YYYYMMDD - do not modify!
// RR = release increments - 00 in DEV branches.
// .XX = incremental changes.
$release = '3.11.15+ (Build: 20230721)';// Human-friendly version name
$branch = '311';

**Comment by IJOL** [comment] 2023-08-03 06:40
to be precise, it happened to me after upgrading moodle to MOODLE_311_STABLE, i try to let the mod upgrader to do the job, so i download the complete moodle, without any mod installed and later let the upgrade process get the needed modules, is in this phase that i get the message reported..

**Comment by danmarsden** [comment] 2023-08-03 22:34
I can't see any issues there related to attendance code, the step that is failing there does a lot of validation checks on your server (not just the code) - could be a server permission error or something else - you could try setting your debug level to developer with display errors on and see if it reports anything else useful, but there's nothing further I can do to help at this stage - let me know if you work anything else out though!

**Comment by danmarsden** [comment] 2023-10-03 07:32
can't reproduce this so I'm closing this off - if you're still having trouble I'd suggest asking for help in the community forums - thanks!

**Closed as completed by danmarsden** 2023-10-03 07:32 UTC
