### ISSUE TITLE
Report page doesn't work properly with Clean and Boost themes

### ISSUE THREAD

**Issue by Urpokarhu1** [danmarsden/moodle-mod_attendance#443] opened 2019-11-19 07:26 UTC
Hello,

Report page doesn't work properly with Clean and Boost themes. 

With Clean there is a weird white-row between user name and email address.
With Boost usernames overlap email address.

![boost](https://user-images.githubusercontent.com/53904029/69125515-a3fbd900-0aae-11ea-9470-4f73d5535dcf.PNG)

![clean](https://user-images.githubusercontent.com/53904029/69125529-aa8a5080-0aae-11ea-9f06-c934deb2f9a3.png)

**Comment by danmarsden** [comment] 2019-11-19 07:45
can you please clarify which version of Moodle you are using and if you are using the latest version of the code from github, or the much older release from the moodle.org plugins database?

**Comment by Urpokarhu1** [comment] 2019-11-20 10:34
Hello,

Moodle 3.5 and version from moodle plugins page:

https://moodle.org/plugins/report/index.php?report=user_sites&pluginid=772

**Comment by danmarsden** [comment] 2019-11-20 21:45
The lastest code is always here in the github repo.

I'm pretty sure this is a duplicate of #388 but it doesn't look like that was backported to the 3.5 branch - feel free to help by submitting a pull request or testing the changes in #388 on your site.

**Comment by NeillM** [comment] 2020-05-06 08:31
We are seeing this in Moodle 3.8

It looks like the rules for making it work in the old clean theme might be the cause, i.e.

#page-mod-attendance-report.has-region-side-pre:not(.empty-region-side-pre) .attendancereporttable .headcol

I could see this rule is still in the master branch.

**Comment by danmarsden** [comment] 2020-05-07 02:17
Thanks Neil, feel free to help to fix by submitting a pull request :-)

**Comment by NeillM** [comment] 2020-05-11 10:03
Pull request with a suggested fix sent.

**Comment by danmarsden** [comment] 2020-07-15 23:23
this one should be resolved now - but please report any further issues as a new bug including a screenshot - thanks!

**Closed by danmarsden** 2020-07-15 23:23 UTC
Labels: bug
